spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/master?allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/master?allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123
  redis:
    session:
      host: 101.101.209.124
      port: 6379
    cache:
      host: 118.67.135.65
      port: 6378
mybatis:
  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
