pipeline 
{ 
    agent any 
    
    tools { 
        gradle 'Gradle 6.6.1'
    } 
    
    stages 
    { 
        stage('git clone') {

            steps {
                checkout scm;
            }
        }
        
        stage ('Build') 
        { 
            steps { 
                //bat "./gradlew.bat build" 
                sh "gradlew clean package -DskipTests=true"
                
            } 
            
        } 
        
        stage('JUnit Test')
        { 
            steps{ 
                sh 'gradlew surefire:test'
                junit '**/build/test-results/test/*.xml' 
                
            } 
            
        } 
        
    } 
    
}
