spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/helpartydb?allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  redis:
    session:
      host: 101.101.209.124
      port: 6379
    cache:
      host: 118.67.135.65
      port: 6379
mybatis:
  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
