## Database 설정
spring:
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/helpartydb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 1234

